name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint check (optional)
        run: |
          pip install flake8
          flake8 app.py

      - name: Streamlit test (headless)
        run: |
          streamlit run app.py --server.headless true &
          sleep 10
          curl -I http://localhost:8501 || exit 1
